# Generated by Django 5.1.4 on 2025-02-05 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderData', models.DateField(default=django.utils.timezone.now)),
                ('prodID', models.IntegerField()),
                ('prodRate', models.IntegerField()),
                ('orderQty', models.IntegerField()),
                ('orderValue', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Master',
            fields=[
                ('prodID', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=50)),
                ('prodRate', models.CharField(max_length=50)),
                ('prodQty', models.CharField(max_length=50)),
            ],
        ),
    ]
